// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../Dictionary ../executionError ../../chunks/languageUtils ../featureset/support/shared".split(" "),function(n,l,m,k,b,p){function q(e,c){return e&&e.domain?"coded-value"===e.domain.type||"codedValue"===e.domain.type?m.convertObjectToArcadeDictionary({type:"codedValue",name:e.domain.name,dataType:p.layerFieldEsriConstants[e.field.type],codedValues:e.domain.codedValues.map(f=>({name:f.name,code:f.code}))},b.defaultTimeZone(c)):m.convertObjectToArcadeDictionary({type:"range",
name:e.domain.name,dataType:p.layerFieldEsriConstants[e.field.type],min:e.domain.min,max:e.domain.max},b.defaultTimeZone(c)):null}n.registerFunctions=function(e){"async"===e.mode&&(e.functions.domain=function(c,f){return e.standardFunctionAsync(c,f,function(){var h=l._asyncToGenerator(function*(d,g,a){b.pcCheck(a,2,3,c,f);if(b.isFeature(a[0]))return d=b.featureFullDomain(a[0],b.toString(a[1]),void 0===a[2]?void 0:b.toNumber(a[2])),q(d,c);if(b.isFeatureSet(a[0]))return yield a[0]._ensureLoaded(),d=
b.getDomain(b.toString(a[1]),a[0],null,void 0===a[2]?void 0:b.toNumber(a[2])),q(d,c);throw new k.ArcadeExecutionError(c,k.ExecutionErrorCodes.InvalidParameter,f);});return function(d,g,a){return h.apply(this,arguments)}}())},e.functions.subtypes=function(c,f){return e.standardFunctionAsync(c,f,function(){var h=l._asyncToGenerator(function*(d,g,a){b.pcCheck(a,1,1,c,f);if(b.isFeature(a[0]))return(d=b.featureSubtypes(a[0]))?m.convertObjectToArcadeDictionary(d,b.defaultTimeZone(c)):null;if(b.isFeatureSet(a[0]))return yield a[0]._ensureLoaded(),
(d=a[0].subtypes())?m.convertObjectToArcadeDictionary(d,b.defaultTimeZone(c)):null;throw new k.ArcadeExecutionError(c,k.ExecutionErrorCodes.InvalidParameter,f);});return function(d,g,a){return h.apply(this,arguments)}}())},e.functions.domainname=function(c,f){return e.standardFunctionAsync(c,f,function(){var h=l._asyncToGenerator(function*(d,g,a){b.pcCheck(a,2,4,c,f);if(b.isFeature(a[0]))return b.featureDomainValueLookup(a[0],b.toString(a[1]),a[2],void 0===a[3]?void 0:b.toNumber(a[3]));if(b.isFeatureSet(a[0]))return yield a[0]._ensureLoaded(),
d=b.getDomain(b.toString(a[1]),a[0],null,void 0===a[3]?void 0:b.toNumber(a[3])),b.getDomainValue(d,a[2]);throw new k.ArcadeExecutionError(c,k.ExecutionErrorCodes.InvalidParameter,f);});return function(d,g,a){return h.apply(this,arguments)}}())},e.signatures.push({name:"domainname",min:2,max:4}),e.functions.domaincode=function(c,f){return e.standardFunctionAsync(c,f,function(){var h=l._asyncToGenerator(function*(d,g,a){b.pcCheck(a,2,4,c,f);if(b.isFeature(a[0]))return b.featureDomainCodeLookup(a[0],
b.toString(a[1]),a[2],void 0===a[3]?void 0:b.toNumber(a[3]));if(b.isFeatureSet(a[0]))return yield a[0]._ensureLoaded(),d=b.getDomain(b.toString(a[1]),a[0],null,void 0===a[3]?void 0:b.toNumber(a[3])),b.getDomainCode(d,a[2]);throw new k.ArcadeExecutionError(c,k.ExecutionErrorCodes.InvalidParameter,f);});return function(d,g,a){return h.apply(this,arguments)}}())},e.signatures.push({name:"domaincode",min:2,max:4}));e.functions.text=function(c,f){return e.standardFunctionAsync(c,f,(h,d,g)=>{b.pcCheck(g,
1,2,c,f);if(b.isFeatureSet(g[0])){d=b.defaultUndefined(g[1],"");if(""===d)return g[0].castToText();if("schema"===d.toLowerCase())return g[0].convertToText("schema",h.abortSignal);if("featureset"===d.toLowerCase())return g[0].convertToText("featureset",h.abortSignal)}else return b.toStringExplicit(g[0],g[1])})};e.functions.gdbversion=function(c,f){return e.standardFunctionAsync(c,f,function(){var h=l._asyncToGenerator(function*(d,g,a){b.pcCheck(a,1,1,c,f);if(b.isFeature(a[0]))return a[0].gdbVersion();
if(b.isFeatureSet(a[0]))return(yield a[0].load()).gdbVersion;throw new k.ArcadeExecutionError(c,k.ExecutionErrorCodes.InvalidParameter,f);});return function(d,g,a){return h.apply(this,arguments)}}())};e.functions.schema=function(c,f){return e.standardFunctionAsync(c,f,function(){var h=l._asyncToGenerator(function*(d,g,a){b.pcCheck(a,1,1,c,f);if(b.isFeatureSet(a[0]))return yield a[0].load(),m.convertObjectToArcadeDictionary(a[0].schema(),b.defaultTimeZone(c));if(b.isFeature(a[0]))return(d=b.featureSchema(a[0]))?
m.convertObjectToArcadeDictionary(d,b.defaultTimeZone(c)):null;throw new k.ArcadeExecutionError(c,k.ExecutionErrorCodes.InvalidParameter,f);});return function(d,g,a){return h.apply(this,arguments)}}())}};Object.defineProperty(n,Symbol.toStringTag,{value:"Module"})});