// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../kernel ../kernel ../../chunks/languageUtils ./centroid ../../geometry/Extent ../../geometry/Geometry ../../geometry/geometryEngineAsync ../../geometry/Multipoint ../../geometry/Point ../../geometry/Polygon ../../geometry/Polyline ../../geometry/support/jsonUtils ../executionError ../Dictionary ../ArcadePortal ../portalUtils ../../core/unitUtils".split(" "),function(C,w,I,m,d,t,x,n,l,D,y,u,v,E,k,A,F,z,J){function G(f){return 0===I.version.indexOf("4.")?
u.fromExtent(f):new u({spatialReference:f.spatialReference,rings:[[[f.xmin,f.ymin],[f.xmin,f.ymax],[f.xmax,f.ymax],[f.xmax,f.ymin],[f.xmin,f.ymin]]]})}function r(f,b,c){d.pcCheck(f,2,2,b,c);if(!(f[0]instanceof n&&f[1]instanceof n||f[0]instanceof n&&null===f[1]||f[1]instanceof n&&null===f[0]||null===f[0]&&null===f[1]))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);}function H(f,b){return B.apply(this,arguments)}function B(){B=w._asyncToGenerator(function*(f,b){if("polygon"!==
f.type&&"polyline"!==f.type&&"extent"!==f.type)return 0;var c=1;if(f.spatialReference.vcsWkid||f.spatialReference.latestVcsWkid){c=t.getMetersPerVerticalUnitForSR(f.spatialReference);var h=J.getMetersPerUnitForSR(f.spatialReference);c/=h}h=0;if("polyline"===f.type)for(var e of f.paths)for(var a=1;a<e.length;a++)h+=t.segmentLength3d(e[a],e[a-1],c);else if("polygon"===f.type)for(a of f.rings){for(e=1;e<a.length;e++)h+=t.segmentLength3d(a[e],a[e-1],c);if(a[0][0]!==a[a.length-1][0]||a[0][1]!==a[a.length-
1][1]||void 0!==a[0][2]&&a[0][2]!==a[a.length-1][2])h+=t.segmentLength3d(a[0],a[a.length-1],c)}else"extent"===f.type&&(h+=2*t.segmentLength3d([f.xmin,f.ymin,0],[f.xmax,f.ymin,0],c),h+=2*t.segmentLength3d([f.xmin,f.ymin,0],[f.xmin,f.ymax,0],c),h=2*h+4*Math.abs(d.defaultUndefined(f.zmax,0)*c-d.defaultUndefined(f.zmin,0)*c));f=new v({hasZ:!1,hasM:!1,spatialReference:f.spatialReference,paths:[[0,0],[0,h]]});return l.planarLength(f,b)});return B.apply(this,arguments)}C.registerFunctions=function(f){"async"===
f.mode&&(f.functions.disjoint=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===a[0]||null===a[1]?!0:l.disjoint(a[0],a[1])})},f.functions.intersects=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===a[0]||null===a[1]?!1:l.intersects(a[0],a[1])})},f.functions.touches=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===
a[0]||null===a[1]?!1:l.touches(a[0],a[1])})},f.functions.crosses=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===a[0]||null===a[1]?!1:l.crosses(a[0],a[1])})},f.functions.within=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===a[0]||null===a[1]?!1:l.within(a[0],a[1])})},f.functions.contains=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);
r(a,b,c);return null===a[0]||null===a[1]?!1:l.contains(a[0],a[1])})},f.functions.overlaps=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===a[0]||null===a[1]?!1:l.overlaps(a[0],a[1])})},f.functions.equals=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{d.pcCheck(a,2,2,b,c);return a[0]===a[1]?!0:a[0]instanceof n&&a[1]instanceof n?l.equals(a[0],a[1]):d.isDate(a[0])&&d.isDate(a[1])?a[0].equals(a[1]):!1})},f.functions.relate=
function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,3,3,b,c);if(a[0]instanceof n&&a[1]instanceof n)return l.relate(a[0],a[1],d.toString(a[2]));if(a[0]instanceof n&&null===a[1]||a[1]instanceof n&&null===a[0]||null===a[0]&&null===a[1])return!1;throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);})},f.functions.intersection=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);
return null===a[0]||null===a[1]?null:l.intersect(a[0],a[1])})},f.functions.union=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);h=[];if(0===a.length)throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.WrongNumberOfParameters,c);if(1===a.length)if(d.isArray(a[0]))for(a=d.autoCastFeatureToGeometry(a[0]),e=0;e<a.length;e++){if(null!==a[e]){if(!(a[e]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h.push(a[e])}}else if(d.isImmutableArray(a[0]))for(a=
d.autoCastFeatureToGeometry(a[0].toArray()),e=0;e<a.length;e++){if(null!==a[e]){if(!(a[e]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h.push(a[e])}}else{if(a[0]instanceof n)return d.fixSpatialReference(m.cloneGeometry(a[0]),b.spatialReference);if(null===a[0])return null;throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);}else for(e=0;e<a.length;e++)if(null!==a[e]){if(!(a[e]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,
c);h.push(a[e])}return 0===h.length?null:l.union(h)})},f.functions.difference=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null!==a[0]&&null===a[1]?m.cloneGeometry(a[0]):null===a[0]?null:l.difference(a[0],a[1])})},f.functions.symmetricdifference=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);r(a,b,c);return null===a[0]&&null===a[1]?null:null===a[0]?m.cloneGeometry(a[1]):null===a[1]?m.cloneGeometry(a[0]):
l.symmetricDifference(a[0],a[1])})},f.functions.clip=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,2,b,c);if(!(a[1]instanceof x)&&null!==a[1])throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return null===a[1]?null:l.clip(a[0],a[1])})},f.functions.cut=function(b,c){return f.standardFunctionAsync(b,
c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,2,b,c);if(!(a[1]instanceof v)&&null!==a[1])throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(null===a[0])return[];if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return null===a[1]?[m.cloneGeometry(a[0])]:l.cut(a[0],a[1])})},f.functions.area=function(b,c){return f.standardFunctionAsync(b,c,function(){var h=w._asyncToGenerator(function*(e,a,g){d.pcCheck(g,1,2,
b,c);g=d.autoCastFeatureToGeometry(g);if(null===g[0])return 0;if(d.isFeatureSet(g[0])){g=yield g[0].sumArea(m.convertSquareUnitsToCode(d.defaultUndefined(g[1],-1)),!1,b.abortSignal);if(b.abortSignal.aborted)throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.Cancelled,c);return g}if(d.isArray(g[0])||d.isImmutableArray(g[0]))return e=d.autoCastArrayOfPointsToPolygon(g[0],b.spatialReference),null===e?0:l.planarArea(e,m.convertSquareUnitsToCode(d.defaultUndefined(g[1],-1)));if(!(g[0]instanceof n))throw new k.ArcadeExecutionError(b,
k.ExecutionErrorCodes.InvalidParameter,c);return l.planarArea(g[0],m.convertSquareUnitsToCode(d.defaultUndefined(g[1],-1)))});return function(e,a,g){return h.apply(this,arguments)}}())},f.functions.areageodetic=function(b,c){return f.standardFunctionAsync(b,c,function(){var h=w._asyncToGenerator(function*(e,a,g){d.pcCheck(g,1,2,b,c);g=d.autoCastFeatureToGeometry(g);if(null===g[0])return 0;if(d.isFeatureSet(g[0])){g=yield g[0].sumArea(m.convertSquareUnitsToCode(d.defaultUndefined(g[1],-1)),!0,b.abortSignal);
if(b.abortSignal.aborted)throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.Cancelled,c);return g}if(d.isArray(g[0])||d.isImmutableArray(g[0]))return e=d.autoCastArrayOfPointsToPolygon(g[0],b.spatialReference),null===e?0:l.geodesicArea(e,m.convertSquareUnitsToCode(d.defaultUndefined(g[1],-1)));if(!(g[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.geodesicArea(g[0],m.convertSquareUnitsToCode(d.defaultUndefined(g[1],-1)))});return function(e,
a,g){return h.apply(this,arguments)}}())},f.functions.length=function(b,c){return f.standardFunctionAsync(b,c,function(){var h=w._asyncToGenerator(function*(e,a,g){d.pcCheck(g,1,2,b,c);g=d.autoCastFeatureToGeometry(g);if(null===g[0])return 0;if(d.isFeatureSet(g[0])){g=yield g[0].sumLength(m.convertLinearUnitsToCode(d.defaultUndefined(g[1],-1)),!1,b.abortSignal);if(b.abortSignal.aborted)throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.Cancelled,c);return g}if(d.isArray(g[0])||d.isImmutableArray(g[0]))return e=
d.autoCastArrayOfPointsToPolyline(g[0],b.spatialReference),null===e?0:l.planarLength(e,m.convertLinearUnitsToCode(d.defaultUndefined(g[1],-1)));if(!(g[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.planarLength(g[0],m.convertLinearUnitsToCode(d.defaultUndefined(g[1],-1)))});return function(e,a,g){return h.apply(this,arguments)}}())},f.functions.length3d=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{d.pcCheck(a,1,2,b,c);a=d.autoCastFeatureToGeometry(a);
if(null===a[0])return 0;if(d.isArray(a[0])||d.isImmutableArray(a[0]))return h=d.autoCastArrayOfPointsToPolyline(a[0],b.spatialReference),null===h?0:!0===h.hasZ?H(h,m.convertLinearUnitsToCode(d.defaultUndefined(a[1],-1))):l.planarLength(h,m.convertLinearUnitsToCode(d.defaultUndefined(a[1],-1)));if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return!0===a[0].hasZ?H(a[0],m.convertLinearUnitsToCode(d.defaultUndefined(a[1],-1))):l.planarLength(a[0],m.convertLinearUnitsToCode(d.defaultUndefined(a[1],
-1)))})},f.functions.lengthgeodetic=function(b,c){return f.standardFunctionAsync(b,c,function(){var h=w._asyncToGenerator(function*(e,a,g){d.pcCheck(g,1,2,b,c);g=d.autoCastFeatureToGeometry(g);if(null===g[0])return 0;if(d.isFeatureSet(g[0])){g=yield g[0].sumLength(m.convertLinearUnitsToCode(d.defaultUndefined(g[1],-1)),!0,b.abortSignal);if(b.abortSignal.aborted)throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.Cancelled,c);return g}if(d.isArray(g[0])||d.isImmutableArray(g[0]))return e=d.autoCastArrayOfPointsToPolyline(g[0],
b.spatialReference),null===e?0:l.geodesicLength(e,m.convertLinearUnitsToCode(d.defaultUndefined(g[1],-1)));if(!(g[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.geodesicLength(g[0],m.convertLinearUnitsToCode(d.defaultUndefined(g[1],-1)))});return function(e,a,g){return h.apply(this,arguments)}}())},f.functions.distance=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);h=a[0];if(d.isArray(a[0])||
d.isImmutableArray(a[0]))h=d.autoCastArrayOfPointsToMultiPoint(a[0],b.spatialReference);e=a[1];if(d.isArray(a[1])||d.isImmutableArray(a[1]))e=d.autoCastArrayOfPointsToMultiPoint(a[1],b.spatialReference);if(!(h instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(!(e instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.distance(h,e,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1)))})},f.functions.distancegeodetic=
function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);h=a[0];e=a[1];if(!(h instanceof y))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(!(e instanceof y))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);const g=new v({paths:[],spatialReference:h.spatialReference});g.addPath([h,e]);return l.geodesicLength(g,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1)))})},f.functions.densify=
function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h=d.toNumber(a[1]);if(isNaN(h))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(0>=h)throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return a[0]instanceof u||a[0]instanceof v?l.densify(a[0],h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],
-1))):a[0]instanceof x?l.densify(G(a[0]),h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1))):a[0]})},f.functions.densifygeodetic=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h=d.toNumber(a[1]);if(isNaN(h))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(0>=h)throw new k.ArcadeExecutionError(b,
k.ExecutionErrorCodes.InvalidParameter,c);return a[0]instanceof u||a[0]instanceof v?l.geodesicDensify(a[0],h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1))):a[0]instanceof x?l.geodesicDensify(G(a[0]),h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1))):a[0]})},f.functions.generalize=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,4,b,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,
c);h=d.toNumber(a[1]);if(isNaN(h))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.generalize(a[0],h,d.toBoolean(d.defaultUndefined(a[2],!0)),m.convertLinearUnitsToCode(d.defaultUndefined(a[3],-1)))})},f.functions.buffer=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h=d.toNumber(a[1]);
if(isNaN(h))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return 0===h?m.cloneGeometry(a[0]):l.buffer(a[0],h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1)))})},f.functions.buffergeodetic=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h=d.toNumber(a[1]);if(isNaN(h))throw new k.ArcadeExecutionError(b,
k.ExecutionErrorCodes.InvalidParameter,c);return 0===h?m.cloneGeometry(a[0]):l.geodesicBuffer(a[0],h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1)))})},f.functions.offset=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,6,b,c);if(null===a[0])return null;if(!(a[0]instanceof u||a[0]instanceof v))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h=d.toNumber(a[1]);if(isNaN(h))throw new k.ArcadeExecutionError(b,
k.ExecutionErrorCodes.InvalidParameter,c);e=d.toNumber(d.defaultUndefined(a[4],10));if(isNaN(e))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);const g=d.toNumber(d.defaultUndefined(a[5],0));if(isNaN(g))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.offset(a[0],h,m.convertLinearUnitsToCode(d.defaultUndefined(a[2],-1)),d.toString(d.defaultUndefined(a[3],"round")).toLowerCase(),e,g)})},f.functions.rotate=function(b,c){return f.standardFunctionAsync(b,
c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,2,3,b,c);h=a[0];if(null===h)return null;if(!(h instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);h instanceof x&&(h=u.fromExtent(h));e=d.toNumber(a[1]);if(isNaN(e))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);a=d.defaultUndefined(a[2],null);if(null===a)return l.rotate(h,e);if(a instanceof y)return l.rotate(h,e,a);throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,
c);})},f.functions.centroid=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,1,1,b,c);if(null===a[0])return null;h=a[0];if(d.isArray(a[0])||d.isImmutableArray(a[0]))h=d.autoCastArrayOfPointsToMultiPoint(a[0],b.spatialReference);if(null===h)return null;if(!(h instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return h instanceof y?d.fixSpatialReference(m.cloneGeometry(a[0]),b.spatialReference):h instanceof
u?h.centroid:h instanceof v?t.centroidPolyline(h):h instanceof D?t.centroidMultiPoint(h):h instanceof x?h.center:null})},f.functions.multiparttosinglepart=function(b,c){return f.standardFunctionAsync(b,c,function(){var h=w._asyncToGenerator(function*(e,a,g){g=d.autoCastFeatureToGeometry(g);d.pcCheck(g,1,1,b,c);a=[];if(null===g[0])return null;if(!(g[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);if(g[0]instanceof y||g[0]instanceof x)return[d.fixSpatialReference(m.cloneGeometry(g[0]),
b.spatialReference)];e=yield l.simplify(g[0]);if(e instanceof u){g=[];a=[];for(var p=0;p<e.rings.length;p++)if(e.isClockwise(e.rings[p])){const q=E.fromJSON({rings:[e.rings[p]],hasZ:!0===e.hasZ,hazM:!0===e.hasM,spatialReference:e.spatialReference.toJSON()});g.push(q)}else a.push({ring:e.rings[p],pt:e.getPoint(p,0)});for(e=0;e<a.length;e++)for(p=0;p<g.length;p++)if(g[p].contains(a[e].pt)){g[p].addRing(a[e].ring);break}return g}if(e instanceof v){g=[];for(a=0;a<e.paths.length;a++)p=E.fromJSON({paths:[e.paths[a]],
hasZ:!0===e.hasZ,hazM:!0===e.hasM,spatialReference:e.spatialReference.toJSON()}),g.push(p);return g}if(g[0]instanceof D){e=d.fixSpatialReference(m.cloneGeometry(g[0]),b.spatialReference);for(g=0;g<e.points.length;g++)a.push(e.getPoint(g));return a}return null});return function(e,a,g){return h.apply(this,arguments)}}())},f.functions.issimple=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,1,1,b,c);if(null===a[0])return!0;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,
k.ExecutionErrorCodes.InvalidParameter,c);return l.isSimple(a[0])})},f.functions.simplify=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,1,1,b,c);if(null===a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.simplify(a[0])})},f.functions.convexhull=function(b,c){return f.standardFunctionAsync(b,c,(h,e,a)=>{a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,1,1,b,c);if(null===
a[0])return null;if(!(a[0]instanceof n))throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);return l.convexHull(a[0])})},f.functions.getuser=function(b,c){return f.standardFunctionAsync(b,c,function(){var h=w._asyncToGenerator(function*(e,a,g){d.pcCheck(g,0,2,b,c);e=d.defaultUndefined(g[1],"");a=!0===e;e=!0===e||!1===e?"":d.toString(e);if(0===g.length||g[0]instanceof F){var p=null;b.services&&b.services.portal&&(p=b.services.portal);0<g.length&&(p=z.getPortal(g[0],p));if(p=
yield z.lookupUser(p,e,a)){p=JSON.parse(JSON.stringify(p));for(var q of["lastLogin","created","modified"])void 0!==p[q]&&null!==p[q]&&(p[q]=new Date(p[q]));return A.convertObjectToArcadeDictionary(p,d.defaultTimeZone(b))}return null}q=null;d.isFeatureSet(g[0])&&(q=g[0]);if(q){a=!1;if(e)return null;yield q.load();g=yield q.getOwningSystemUrl();if(!g)return!e&&(p=yield q.getIdentityUser())?A.convertObjectToArcadeDictionary({username:p},d.defaultTimeZone(b)):null;q=null;b.services&&b.services.portal&&
(q=b.services.portal);q=z.getPortal(new F(g),q);if(q=yield z.lookupUser(q,e,a)){q=JSON.parse(JSON.stringify(q));for(p of["lastLogin","created","modified"])void 0!==q[p]&&null!==q[p]&&(q[p]=new Date(q[p]));return A.convertObjectToArcadeDictionary(q,d.defaultTimeZone(b))}return null}throw new k.ArcadeExecutionError(b,k.ExecutionErrorCodes.InvalidParameter,c);});return function(e,a,g){return h.apply(this,arguments)}}())})};Object.defineProperty(C,Symbol.toStringTag,{value:"Module"})});