// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ./ArcadeDate ./executionError ./ImmutableArray ../chunks/languageUtils ../geometry/Geometry".split(" "),function(q,p,l,u,f,r){function n(e,g,c=!1){if(null===e||void 0===e)return null;if(f.isNumber(e))return f.toNumber(e);if(f.isBoolean(e))return f.toBoolean(e);if(f.isString(e))return f.toString(e);if(f.isDate(e))return f.toDate(e,g);if(f.isArray(e)){var b=[];for(var d of e)b.push(n(d,g,c));return b}d=new t;d.immutable=!1;for(b of Object.keys(e)){const a=
e[b];void 0!==a&&d.setField(b,n(a,g,c))}d.immutable=c;return d}let t=function(){function e(c){this.declaredClass="esri.arcade.Dictionary";this.attributes=null;this.plain=!1;this.immutable=!0;this.attributes=c instanceof e?c.attributes:void 0===c?{}:null===c?{}:c}var g=e.prototype;g.field=function(c){const b=c.toLowerCase(),d=this.attributes[c];if(void 0!==d)return d;for(const a in this.attributes)if(a.toLowerCase()===b)return this.attributes[a];throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.FieldNotFound,
null,{key:c});};g.setField=function(c,b){if(this.immutable)throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.Immutable,null);if(f.isFunctionParameter(b))throw new l.ArcadeExecutionError(null,l.ExecutionErrorCodes.NoFunctionInDictionary,null);const d=c.toLowerCase();b instanceof Date&&(b=p.ArcadeDate.dateJSToArcadeDate(b));if(void 0===this.attributes[c])for(const a in this.attributes)if(a.toLowerCase()===d){this.attributes[a]=b;return}this.attributes[c]=b};g.hasField=function(c){const b=
c.toLowerCase();if(void 0!==this.attributes[c])return!0;for(const d in this.attributes)if(d.toLowerCase()===b)return!0;return!1};g.keys=function(){let c=[];for(const b in this.attributes)c.push(b);return c=c.sort()};g.castToText=function(c=!1){let b="";for(const d in this.attributes){""!==b&&(b+=",");const a=this.attributes[d];null==a?b+=JSON.stringify(d)+":null":f.isBoolean(a)||f.isNumber(a)||f.isString(a)?b+=JSON.stringify(d)+":"+JSON.stringify(a):a instanceof r?b+=JSON.stringify(d)+":"+f.toStringExplicit(a):
a instanceof u?b+=JSON.stringify(d)+":"+f.toStringExplicit(a,null,c):a instanceof Array?b+=JSON.stringify(d)+":"+f.toStringExplicit(a,null,c):a instanceof p.ArcadeDate?b=c?b+(JSON.stringify(d)+":"+JSON.stringify(a.getTime())):b+(JSON.stringify(d)+":"+a.stringify()):null!==a&&"object"===typeof a&&void 0!==a.castToText&&(b+=JSON.stringify(d)+":"+a.castToText(c))}return"{"+b+"}"};e.convertObjectToArcadeDictionary=function(c,b,d=!0){const a=new e;a.immutable=!1;for(const k in c){const h=c[k];void 0!==
h&&a.setField(k.toString(),n(h,b))}a.immutable=d;return a};e.convertJsonToArcade=function(c,b,d=!1){return n(c,b,d)};g.castAsJson=function(c=null){const b={};for(let d in this.attributes){const a=this.attributes[d];void 0!==a&&(c?.keyTranslate&&(d=c.keyTranslate(d)),b[d]=f.castAsJson(a,c))}return b};g.castDictionaryValueAsJsonAsync=function(){var c=q._asyncToGenerator(function*(b,d,a,k=null,h){a=yield f.castAsJsonAsync(a,k,h);return b[d]=a});return function(b,d,a){return c.apply(this,arguments)}}();
g.castAsJsonAsync=function(){var c=q._asyncToGenerator(function*(b=null,d=null){const a={},k=[];for(let h in this.attributes){const m=this.attributes[h];d?.keyTranslate&&(h=d.keyTranslate(h));void 0!==m&&(f.isSimpleType(m)||m instanceof r||m instanceof p.ArcadeDate?a[h]=f.castAsJson(m,d):k.push(this.castDictionaryValueAsJsonAsync(a,h,m,b,d)))}0<k.length&&(yield Promise.all(k));return a});return function(){return c.apply(this,arguments)}}();return e}();return t});