// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.26/esri/copyright.txt for details.
//>>built
define("exports ../chunks/_rollupPluginBabelHelpers ../request ./featureSetCollection ./featureset/actions/AttributeFilter ./featureset/actions/GroupBy ./featureset/actions/OrderBy ./featureset/actions/SpatialFilter ./featureset/actions/Top ./featureset/sources/FeatureLayerDynamic ./featureset/sources/FeatureLayerMemory ./featureset/sources/FeatureLayerRelated ./featureset/support/cache ./featureset/support/errorsupport ./featureset/support/FeatureSet ./featureset/support/shared ../core/sql/WhereClause ../layers/FeatureLayer ../portal/PortalItem".split(" "),
function(r,n,u,F,K,L,M,N,O,P,Q,R,m,G,S,H,T,q,U){function v(a,f){return w.apply(this,arguments)}function w(){w=n._asyncToGenerator(function*(a,f){if(m.applicationCache){var g=m.applicationCache.getLayerInfo(a);if(g)return g=yield g,new q({url:a,outFields:f,sourceJSON:g});const h=new q({url:a,outFields:f});f=n._asyncToGenerator(function*(){yield h.load();return h.sourceJSON})();if(m.applicationCache){m.applicationCache.setLayerInfo(a,f);try{return yield f,h}catch(b){throw m.applicationCache.clearLayerInfo(a),
b;}}yield f;return h}return new q({url:a,outFields:f})});return w.apply(this,arguments)}function x(a,f,g,h,b){return y.apply(this,arguments)}function y(){y=n._asyncToGenerator(function*(a,f,g,h,b,k=null){a=yield v(a,["*"]);return t(a,f,g,h,b,k)});return y.apply(this,arguments)}function t(a,f=null,g=null,h=!0,b=null,k=null){f={layer:a,spatialReference:f,outFields:g,includeGeometry:h,lrucache:b,interceptor:k};return!0===a._hasMemorySource()?new Q(f):new P(f)}function V(a){return z.apply(this,arguments)}
function z(){z=n._asyncToGenerator(function*(a){if(null!==m.applicationCache){var f=m.applicationCache.getLayerInfo(a);if(null!==f)return f}f=n._asyncToGenerator(function*(){const g=yield u(a,{responseType:"json",query:{f:"json"}});return g.data?g.data:null})();if(null!==m.applicationCache){m.applicationCache.setLayerInfo(a,f);try{return yield f}catch(g){throw m.applicationCache.clearLayerInfo(a),g;}}return f});return z.apply(this,arguments)}function W(a,f){return A.apply(this,arguments)}function A(){A=
n._asyncToGenerator(function*(a,f){const g="QUERYDATAELEMTS:"+f.toString()+":"+a;if(null!==m.applicationCache){var h=m.applicationCache.getLayerInfo(g);if(null!==h)return h}h=n._asyncToGenerator(function*(){var b=yield u(a+"/queryDataElements",{method:"post",responseType:"json",query:{layers:JSON.stringify([f.toString()]),f:"json"}});if(b.data&&(b=b.data,b.layerDataElements&&b.layerDataElements[0]))return b.layerDataElements[0];throw new G.FeatureSetError(G.FeatureSetErrorCodes.DataElementsNotFound);
})();if(null!==m.applicationCache){m.applicationCache.setLayerInfo(g,h);try{return yield h}catch(b){throw m.applicationCache.clearLayerInfo(g),b;}}return h});return A.apply(this,arguments)}function I(a){return B.apply(this,arguments)}function B(){B=n._asyncToGenerator(function*(a){if(null!==m.applicationCache){var f=m.applicationCache.getLayerInfo(a);if(null!==f)return f}f=n._asyncToGenerator(function*(){var g=yield u(a,{responseType:"json",query:{f:"json"}});return g.data?(g=g.data,g.layers||(g.layers=
[]),g.tables||(g.tables=[]),g):{layers:[],tables:[]}})();if(null!==m.applicationCache){m.applicationCache.setLayerInfo(a,f);try{return yield f}catch(g){throw m.applicationCache.clearLayerInfo(a),g;}}return f});return B.apply(this,arguments)}function C(){C=n._asyncToGenerator(function*(a,f){var g=3,h=[],b=null,k={},c=null;c=yield I(a);if(c.controllerDatasetLayers&&void 0!==c.controllerDatasetLayers.utilityNetworkLayerId&&null!==c.controllerDatasetLayers.utilityNetworkLayerId){if(c.layers)for(var e of c.layers)k[e.id]=
e.name;if(c.tables)for(var d of c.tables)k[d.id]=d.name;e=c.controllerDatasetLayers.utilityNetworkLayerId;if(c=yield W(a,e)){(b=c)&&b.dataElement&&void 0!==b.dataElement.schemaGeneration&&(g=b.dataElement.schemaGeneration);c={};b.dataElement.domainNetworks||(b.dataElement.domainNetworks=[]);for(var l of b.dataElement.domainNetworks){for(const p of l.edgeSources?l.edgeSources:[])d={layerId:p.layerId,sourceId:p.sourceId,className:k[p.layerId]?k[p.layerId]:null},d.className&&(c[d.className]=d);for(const p of l.junctionSources?
l.junctionSources:[])d={layerId:p.layerId,sourceId:p.sourceId,className:k[p.layerId]?k[p.layerId]:null},d.className&&(c[d.className]=d)}if(b.dataElement.terminalConfigurations)for(const p of b.dataElement.terminalConfigurations)for(const J of p.terminals)h.push({terminalId:J.terminalId,terminalName:J.terminalName});k=yield V(a+"/"+e);if(k.systemLayers&&void 0!==k.systemLayers.associationsTableId&&null!==k.systemLayers.associationsTableId)return l=[],4<=g&&(l.push("STATUS"),l.push("PERCENTALONG")),
a=yield x(a+"/"+k.systemLayers.associationsTableId.toString(),f,["OBJECTID","FROMNETWORKSOURCEID","TONETWORKSOURCEID","FROMGLOBALID","TOGLOBALID","TOTERMINALID","FROMTERMINALID","ASSOCIATIONTYPE","ISCONTENTVISIBLE","GLOBALID",...l],!1,null,null),yield a.load(),4<=g&&(a=a.filter(T.WhereClause.create("STATUS NOT IN (1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62,63)",
a.getFieldsIndex())),yield a.load()),{lkp:c,associations:a,unVersion:g,terminals:h}}}return{associations:null,unVersion:g,lkp:null,terminals:[]}});return C.apply(this,arguments)}function D(){D=n._asyncToGenerator(function*(a,f,g,h=null,b=null,k=!0,c=null,e=null){var d=a.serviceUrl();if(!d)return null;d="/"===d.charAt(d.length-1)?d+f.relatedTableId.toString():d+"/"+f.relatedTableId.toString();d=yield x(d,h,b,k,c,e);return new R({layer:a,relatedLayer:d,relationship:f,objectId:g,spatialReference:h,outFields:b,
includeGeometry:k,lrucache:c,interceptor:e})});return D.apply(this,arguments)}function E(){E=n._asyncToGenerator(function*(a,f,g,h,b,k,c,e=null){if(m.applicationCache){var d=m.applicationCache.getLayerInfo(a+":"+k.url);if(d)return a=yield d,f=new q({url:H.extractServiceUrl(a.url)+"/"+f,outFields:["*"]}),t(f,g,h,b,c,e)}d=(new U({id:a,portal:k})).load();m.applicationCache&&m.applicationCache.setLayerInfo(a+":"+k.url,d);try{const l=yield d,p=new q({url:H.extractServiceUrl(l.url??"")+"/"+f,outFields:["*"]});
return t(p,g,h,b,c,e)}catch(l){throw m.applicationCache&&m.applicationCache.clearLayerInfo(a+":"+k.url),l;}});return E.apply(this,arguments)}K.registerAction();L.registerAction();M.registerAction();N.registerAction();O.registerAction();let X=function(a){function f(h,b=null,k=null,c=null){var e=a.call(this)||this;e._map=h;e._overridespref=b;e._lrucache=k;e._interceptor=c;e._instantLayers=[];return e}n._inheritsLoose(f,a);var g=f.prototype;g._makeAndAddFeatureSet=function(h,b=!0,k=null){const c=t(h,
this._overridespref,null===k?["*"]:k,b,this._lrucache,this._interceptor);this._instantLayers.push({featureset:c,opitem:h,includeGeometry:b,outFields:JSON.stringify(k)});return c};g.featureSetByName=function(){var h=n._asyncToGenerator(function*(b,k=!0,c=null){if(void 0!==this._map.loaded&&void 0!==this._map.load&&!1===this._map.loaded)return yield this._map.load(),this.featureSetByName(b,k,c);null===c&&(c=["*"]);c=c.slice(0);c=c.sort();var e=JSON.stringify(c);for(let d=0;d<this._instantLayers.length;d++){const l=
this._instantLayers[d];if(l.opitem.title===b&&l.includeGeometry===k&&l.outFields===e)return this._instantLayers[d].featureset}if(e=this._map.allLayers.find(d=>d instanceof q&&d.title===b?!0:!1))return this._makeAndAddFeatureSet(e,k,c);if(this._map.tables&&(e=this._map.tables.find(d=>d.title&&d.title===b||d.title&&d.title===b?!0:!1))){if(e instanceof q)return this._makeAndAddFeatureSet(e,k,c);e._materializedTable||(e._materializedTable=new q(e.outFields?e:{...e,outFields:["*"]}));yield e._materializedTable.load();
return this._makeAndAddFeatureSet(e._materializedTable,k,c)}return null});return function(b){return h.apply(this,arguments)}}();g.featureSetById=function(){var h=n._asyncToGenerator(function*(b,k=!0,c=["*"]){if(void 0!==this._map.loaded&&void 0!==this._map.load&&!1===this._map.loaded)return yield this._map.load(),this.featureSetById(b,k,c);null===c&&(c=["*"]);c=c.slice(0);c=c.sort();var e=JSON.stringify(c);for(let d=0;d<this._instantLayers.length;d++){const l=this._instantLayers[d];if(l.opitem.id===
b&&l.includeGeometry===k&&l.outFields===e)return this._instantLayers[d].featureset}if(e=this._map.allLayers.find(d=>d instanceof q&&d.id===b?!0:!1))return this._makeAndAddFeatureSet(e,k,c);if(this._map.tables&&(e=this._map.tables.find(d=>d.id===b?!0:!1))){if(e instanceof q)return this._makeAndAddFeatureSet(e,k,c);e._materializedTable||(e._materializedTable=new q({...e,outFields:["*"]}));yield e._materializedTable.load();return this._makeAndAddFeatureSet(e._materializedTable,k,c)}return null});return function(b){return h.apply(this,
arguments)}}();return f}(F),Y=function(a){function f(h,b=null,k=null,c=null){var e=a.call(this)||this;e._url=h;e._overridespref=b;e._lrucache=k;e._interceptor=c;e.metadata=null;e._instantLayers=[];return e}n._inheritsLoose(f,a);var g=f.prototype;g._makeAndAddFeatureSet=function(h,b=!0,k=null){const c=t(h,this._overridespref,null===k?["*"]:k,b,this._lrucache);this._instantLayers.push({featureset:c,opitem:h,includeGeometry:b,outFields:JSON.stringify(k)});return c};g._loadMetaData=function(){var h=n._asyncToGenerator(function*(){const b=
yield I(this._url);return this.metadata=b});return function(){return h.apply(this,arguments)}}();g.load=function(){return this._loadMetaData()};g.clone=function(){return new f(this._url,this._overridespref,this._lrucache,this._interceptor)};g.featureSetByName=function(){var h=n._asyncToGenerator(function*(b,k=!0,c=null){null===c&&(c=["*"]);c=c.slice(0);c=c.sort();var e=JSON.stringify(c);for(var d=0;d<this._instantLayers.length;d++){const l=this._instantLayers[d];if(l.opitem.title===b&&l.includeGeometry===
k&&l.outFields===e)return this._instantLayers[d].featureset}e=yield this._loadMetaData();d=null;for(const l of e.layers?e.layers:[])l.name===b&&(d=l);if(!d)for(const l of e.tables?e.tables:[])l.name===b&&(d=l);return d?(b=yield v(this._url+"/"+d.id,["*"]),this._makeAndAddFeatureSet(b,k,c)):null});return function(b){return h.apply(this,arguments)}}();g.featureSetById=function(){var h=n._asyncToGenerator(function*(b,k=!0,c=["*"]){null===c&&(c=["*"]);c=c.slice(0);c=c.sort();var e=JSON.stringify(c);b=
null!==b&&void 0!==b?b.toString():"";for(var d=0;d<this._instantLayers.length;d++){const l=this._instantLayers[d];if(l.opitem.id===b&&l.includeGeometry===k&&l.outFields===e)return this._instantLayers[d].featureset}e=yield this._loadMetaData();d=null;for(const l of e.layers?e.layers:[])null!==l.id&&void 0!==l.id&&l.id.toString()===b&&(d=l);if(!d)for(const l of e.tables?e.tables:[])null!==l.id&&void 0!==l.id&&l.id.toString()===b&&(d=l);return d?(b=yield v(this._url+"/"+d.id,["*"]),this._makeAndAddFeatureSet(b,
k,c)):null});return function(b){return h.apply(this,arguments)}}();n._createClass(f,[{key:"url",get:function(){return this._url}}]);return f}(F);r.constructAssociationMetaDataFeatureSetFromUrl=function(a,f){return C.apply(this,arguments)};r.constructFeatureSet=t;r.constructFeatureSetFromPortalItem=function(a,f,g,h,b,k,c){return E.apply(this,arguments)};r.constructFeatureSetFromRelationship=function(a,f,g){return D.apply(this,arguments)};r.constructFeatureSetFromUrl=x;r.convertToFeatureSet=function(a,
f,g,h,b){if(null===a)return null;if(a instanceof q){switch(f){case "datasource":return t(a,b,a.outFields,!0,g,h).getDataSourceFeatureSet();case "parent":return t(a,b,a.outFields,!0,g,h);case "root":return t(a,b,a.outFields,!0,g,h)}return null}if(a instanceof S)switch(f){case "datasource":return a.getDataSourceFeatureSet();case "parent":return a;case "root":return a.getRootFeatureSet()}return null};r.createFeatureSetCollectionFromMap=function(a,f,g=null,h=null){return new X(a,f,g,h)};r.createFeatureSetCollectionFromService=
function(a,f,g=null,h=null){return new Y(a,f,g,h)};r.initialiseMetaDataCache=function(){null===m.applicationCache&&(m.applicationCache=new m)};Object.defineProperty(r,Symbol.toStringTag,{value:"Module"})});